# This file runs on push request to main branch or manually.
# It clones the repository, installs the library and runs the tests.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install library
        run: python setup.py install
      - name: Run card test
        run: python test.py card
      - name: Run deck test
        run: python test.py deck